### ISSUE TITLE
v1 is out of date

### ISSUE THREAD

**Issue by zommerfelds** [nschloe/action-cached-lfs-checkout#28]
According to https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations (point 3) it would be recommended to make v1 point to the most recent v1.x.x version. I believe the v1 in this repo is not outdated though.

For example, in https://github.com/nschloe/action-cached-lfs-checkout/blob/v1/action.yml I'm still seeing the deprecated `::set-output`.

Thanks for offering this action BTW!

**Comment by cmey** [comment]
> I believe the v1 in this repo is not outdated though.

I believe it is outdated!  As you said, `[v1](https://github.com/nschloe/action-cached-lfs-checkout/releases/tag/v1)` doesn't point to the same code as the latest `[v1.2.1](https://github.com/nschloe/action-cached-lfs-checkout/releases/tag/v1.2.1)`.

**Comment by nschloe** [comment]
Fixed.
