### ISSUE TITLE
Pull only one file?

### ISSUE THREAD

**Issue by sam-hoffman** [nschloe/action-cached-lfs-checkout#3]
We have development assets (jupyter notebooks and development data) in LFS, but we really only need to pull one file for our Github Action to work. Is there a way to pass only one file to your action? If not, would you accept a PR?

**Comment by nschloe** [comment]
Use the new `include` option, see README.

**Comment by sam-hoffman** [comment]
Thanks so much, I really appreciate it! I made one comment on the PR :)
