### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by gemal** [nschloe/action-cached-lfs-checkout#40]
any chance to update to actions/checkout@v4 ?

**Comment by marcofugaro** [comment]
Same warning, thanks for the action it's really useful 🙏

**Comment by zommerfelds** [comment]
There are open pull requests here:

https://github.com/nschloe/action-cached-lfs-checkout/pull/36
https://github.com/nschloe/action-cached-lfs-checkout/pull/35

It would be nice if they could be merged. Alternatively I created https://github.com/nschloe/action-cached-lfs-checkout/pull/42

Meanwhile I made a release in my own fork: just replace the existing by `zommerfelds/action-cached-lfs-checkout@v2` and it should get rid of the warnings. If other people test this out too it would be helpful to see if there are any breaking changes. For me it worked fine.

**Comment by nschloe** [comment]
Fixed now, release imminent.
